In [189]:
import numpy as np
import pandas as pd

In [190]:
df=pd.read_csv("../../Bigdata Files/diabetes.csv")
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [191]:
df["Outcome"].value_counts()

0    500
1    268
Name: Outcome, dtype: int64

In [192]:
# common steps

In [193]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [194]:
df.tail()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0

In [195]:
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [196]:
df.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [197]:
df.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [198]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [199]:
df.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [200]:
# Seprate input and output

In [201]:
# X=df.iloc[:,:-1]

In [202]:
X=df.drop("Outcome",axis=1).values

In [203]:
X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [204]:
# y=df.iloc[:,-1]

In [205]:
y=df["Outcome"].values

In [206]:
y

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,

In [207]:
# Training and Testing data
from sklearn.model_selection import train_test_split

In [208]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)

In [209]:
X_train

array([[  9.   , 112.   ,  82.   , ...,  34.2  ,   0.26 ,  36.   ],
       [  2.   , 128.   ,  64.   , ...,  40.   ,   1.101,  24.   ],
       [  6.   , 129.   ,  90.   , ...,  19.6  ,   0.582,  60.   ],
       ...,
       [  6.   ,  93.   ,  50.   , ...,  28.7  ,   0.356,  23.   ],
       [  2.   , 155.   ,  52.   , ...,  38.7  ,   0.24 ,  25.   ],
       [  4.   , 110.   ,  66.   , ...,  31.9  ,   0.471,  29.   ]])

In [210]:
X_test

array([[0.000e+00, 1.280e+02, 6.800e+01, ..., 3.050e+01, 1.391e+00,
        2.500e+01],
       [1.000e+00, 1.140e+02, 6.600e+01, ..., 3.810e+01, 2.890e-01,
        2.100e+01],
       [2.000e+00, 9.900e+01, 0.000e+00, ..., 2.220e+01, 1.080e-01,
        2.300e+01],
       ...,
       [8.000e+00, 1.250e+02, 9.600e+01, ..., 0.000e+00, 2.320e-01,
        5.400e+01],
       [4.000e+00, 1.340e+02, 7.200e+01, ..., 2.380e+01, 2.770e-01,
        6.000e+01],
       [7.000e+00, 1.610e+02, 8.600e+01, ..., 3.040e+01, 1.650e-01,
        4.700e+01]])

In [211]:
y_train

array([1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,

In [212]:
y_test

array([1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1])

In [213]:
# input data are in different range
# Scaling (Normalization) : input data "convrted into same range"
# i/p converted into normalized form

In [214]:
# StandarScaler is a the Scaling method
# others are minmax scaler bimaryScalar

In [215]:
# Standard Scaler based on equation
# z=(x-u)/s
# x : is the column value (eg glucose)
# u : mean of training sample
# s : standard deviation of training data

In [216]:
from sklearn.preprocessing import StandardScaler

In [217]:
scaler=StandardScaler()
scaler.fit(X_train) # we need to only fit training sample
X_train=scaler.transform(X_train)
X_test=scaler.transform(X_test)

In [218]:
X_test

array([[-1.12944303,  0.23831519, -0.04168365, ..., -0.18289839,
         2.84904417, -0.70281311],
       [-0.83387241, -0.20276152, -0.14603852, ...,  0.82214389,
        -0.52644011, -1.05578074],
       [-0.5383018 , -0.67534371, -3.58974929, ..., -1.28051036,
        -1.08085268, -0.87929693],
       ...,
       [ 1.23512191,  0.14379875,  1.41928455, ..., -4.21629176,
        -0.70103413,  1.85620222],
       [ 0.05283944,  0.42734806,  0.16702609, ..., -1.06892251,
        -0.56319675,  2.38565367],
       [ 0.93955129,  1.277996  ,  0.8975102 , ..., -0.19612263,
        -0.90625867,  1.23850886]])

In [219]:
X_train

array([[ 1.53069253e+00, -2.65772478e-01,  6.88800452e-01, ...,
         3.06398512e-01, -6.15268645e-01,  2.67847877e-01],
       [-5.38301796e-01,  2.38315188e-01, -2.50393393e-01, ...,
         1.07340447e+00,  1.96075883e+00, -7.91055018e-01],
       [ 6.43980676e-01,  2.69820668e-01,  1.10621994e+00, ...,
        -1.62434061e+00,  3.71034383e-01,  2.38565367e+00],
       ...,
       [ 6.43980676e-01, -8.64376581e-01, -9.80877495e-01, ...,
        -4.20934719e-01, -3.21215568e-01, -8.79296925e-01],
       [-5.38301796e-01,  1.08896312e+00, -8.76522624e-01, ...,
         9.01489338e-01, -6.76529702e-01, -7.02813110e-01],
       [ 5.28394401e-02, -3.28783436e-01, -1.46038522e-01, ...,
         2.24097931e-03,  3.10355135e-02, -3.49845478e-01]])

In [220]:
# Model knn creation

In [221]:
# package name : sklearn 
# module name : neighbors
# function name :KNeighborsClassifier
from sklearn.neighbors import KNeighborsClassifier

In [222]:
knn=KNeighborsClassifier(n_neighbors=7)
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=7)

In [223]:
print(knn.predict([[1,0,48,20,0,24.7,0.14,60]]))

[0]


In [224]:
print(knn.predict([[0,67,80,30,27,27.5,1.0,17]]))

[1]


In [225]:
print(knn.predict([[1,0,50,20,0,24.7,0.14,60]]))

[0]


In [226]:
print(knn.predict([[6,100,36,0,0,34.7,1.80,50]]))

[1]


In [227]:
print(knn.predict([[0,100,32,0,10,24.7,0.14,60]]))

[1]


In [228]:
print(knn.predict([[0,80,48,48,18,30.7,1.22,20]]))

[1]


In [229]:
y_pred=knn.predict(X_test)
y_pred

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0])

In [230]:
y_test

array([1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1])

In [231]:
print(knn.predict([[1,85,66,29,0,26.6,0.351,31]]))

[1]


In [232]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [233]:
result = confusion_matrix(y_test,y_pred)
result

array([[130,  26],
       [ 34,  41]])

In [234]:
score = accuracy_score(y_test,y_pred)
score

0.7402597402597403

# Performance Evaluation 

**Using Confusion Matrics to evaluate Performance**

**TP        FP
FN        TN**

- TP : True Positive
- TN : True Negative
- FP : False Postive
- FN : False Negative

- y_test : Actual result
- y_pred : Machine predicted Result

######  TP :
- 1 =====> 1

###### TN:
- 0 ====> 0

**------------------------------------------**

###### FP:
- 0 ====> 1

###### FN :
- 1 ====> 0

In [235]:
"""
y_test : 1 0 0 1 0 1 0 1 1 1 0 1 1 0 1 0 1 0 1
y_pred : 1 0 0 0 1 0 1 0 1 0 1 0 1 0 0 1 0 0 0

TP : 3
TN : 4
FP : 4
FN : 7

"""

'\ny_test : 1 0 0 1 0 1 0 1 1 1 0 1 1 0 1 0 1 0 1\ny_pred : 1 0 0 0 1 0 1 0 1 0 1 0 1 0 0 1 0 0 0\n\nTP : 3\nTN : 4\nFP : 4\nFN : 7\n\n'

## Classification
**--------------------**

##### 4 Performance

###### Accuracy score
###### Recall
###### Precision
###### F1-Score

###### Accuracy Score
**---------------------**

**Score = TP+TN/(TP+TN+FP+FN)**